Add exclusion file
banool/recreation-gov-campsite-checker pull request #56
Opened 2023-04-10 21:01 UTC by karstenpatzwaldt

Add the option to specify a file with site IDs to ignore. This is useful to filter out things like group campsites.

2023-04-10 21:48 UTC, banool requested changes
Thanks a lot for this! Just a couple of comments.

2023-04-10 21:48 UTC, banool commented on camping.py
> +            new_lines.append(line)
Should you use `line.strip()` here too?

2023-04-10 21:48 UTC, banool commented on camping.py
> +import re
Is this used?

2023-04-10 23:23 UTC, karstenpatzwaldt commented
Addressed your ocmments

2023-04-11 12:30 UTC, banool commented
Thanks a lot!!

2023-04-11 12:30 UTC, merged